### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by riedgar-ms** [microsoft/adatest#23]
Just tried a `pip install adatest` in a fresh conda environment with Python 3.9:
```bash
(adt-39) riedgar@jormungand:~$ pip install adatest
Collecting adatest
  Using cached adatest-0.3.0.tar.gz (67 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8a8ikdp8/adatest_00e6da821d3a46719714104947654cc0/setup.py", line 18, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Looks like the `requirements.txt` didn't make it into the wheel?

**Comment by Harsha-Nori** [comment]
Thanks for reporting this! This should be fixed as of [v0.3.3](https://pypi.org/project/adatest/0.3.3/).
